name: CI/CD Lint, Prettify, Tests and Build

on:
  push:
    branches:
      - 'main'

jobs:
  lint-prettify-test-and-build:
    runs-on: ubuntu-latest

    steps:
        
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          
      - name: Install dependencies
        working-directory: ./tdw-felix-scherer
        run: pnpm install

      - name: Run lint
        working-directory: ./tdw-felix-scherer
        run: pnpm run lint

      - name: Run Prettier
        working-directory: ./tdw-felix-scherer
        run: pnpm run prettier

      - name: Run Tests
        working-directory: ./tdw-felix-scherer
        run: pnpm run test

      - name: Run Build
        working-directory: ./tdw-felix-scherer
        run: pnpm run build

      - name: Run Deploy
        working-directory: ./tdw-felix-scherer
        run: npx netlify-cli deploy --site ${{secrets.NETLIFY_SITE_ID}} --auth ${{secrets.NETLIFY_AUTH_TOKEN}} --prod
